# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf97cefa3065b8b6a6046d66dd10a56c29c56308c641c74115aea02c9abf5a04ffae830a81eaf46d8f2e62f0124df8fc8fe0c10b0ef3f1024f54f73e8b4f8e45

test:
  secret_key_base: dcc4e86b3492f4d9777b72fc802000a9c6e02ba046ea7142c37a390365f045fb56e28246ceeef0d68bbc8bafe5240d4091e84e7c535105fd7bc9e3021c7f2a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
