require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DatasourcesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Datasource. As you add validations to Datasource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:datasource)
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatasourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all datasources as @datasources" do
      datasource = Datasource.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:datasources)).to eq([datasource])
    end
  end

  describe "GET #show" do
    it "assigns the requested datasource as @datasource" do
      datasource = Datasource.create! valid_attributes
      get :show, {:id => datasource.to_param}, valid_session
      expect(assigns(:datasource)).to eq(datasource)
    end
  end

  describe "GET #new" do
    it "assigns a new datasource as @datasource" do
      get :new, {}, valid_session
      expect(assigns(:datasource)).to be_a_new(Datasource)
    end
  end

  describe "GET #edit" do
    it "assigns the requested datasource as @datasource" do
      datasource = Datasource.create! valid_attributes
      get :edit, {:id => datasource.to_param}, valid_session
      expect(assigns(:datasource)).to eq(datasource)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Datasource" do
        expect {
          post :create, {:datasource => valid_attributes}, valid_session
        }.to change(Datasource, :count).by(1)
      end

      it "assigns a newly created datasource as @datasource" do
        post :create, {:datasource => valid_attributes}, valid_session
        expect(assigns(:datasource)).to be_a(Datasource)
        expect(assigns(:datasource)).to be_persisted
      end

      it "redirects to the created datasource" do
        post :create, {:datasource => valid_attributes}, valid_session
        expect(response).to redirect_to(Datasource.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved datasource as @datasource" do
        post :create, {:datasource => invalid_attributes}, valid_session
        expect(assigns(:datasource)).to be_a_new(Datasource)
      end

      it "re-renders the 'new' template" do
        post :create, {:datasource => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        FactoryGirl.attributes_for(:datasource)
      }

      it "updates the requested datasource" do
        datasource = Datasource.create! valid_attributes
        put :update, {:id => datasource.to_param, :datasource => new_attributes}, valid_session
        datasource.reload
        expect(controller.notice).to eq('Datasource was successfully updated.')
      end

      it "assigns the requested datasource as @datasource" do
        datasource = Datasource.create! valid_attributes
        put :update, {:id => datasource.to_param, :datasource => valid_attributes}, valid_session
        expect(assigns(:datasource)).to eq(datasource)
      end

      it "redirects to the datasource" do
        datasource = Datasource.create! valid_attributes
        put :update, {:id => datasource.to_param, :datasource => valid_attributes}, valid_session
        expect(response).to redirect_to(datasource)
      end
    end

    context "with invalid params" do
      it "assigns the datasource as @datasource" do
        datasource = Datasource.create! valid_attributes
        put :update, {:id => datasource.to_param, :datasource => invalid_attributes}, valid_session
        expect(assigns(:datasource)).to eq(datasource)
      end

      it "re-renders the 'edit' template" do
        datasource = Datasource.create! valid_attributes
        put :update, {:id => datasource.to_param, :datasource => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested datasource" do
      datasource = Datasource.create! valid_attributes
      expect {
        delete :destroy, {:id => datasource.to_param}, valid_session
      }.to change(Datasource, :count).by(-1)
    end

    it "redirects to the datasources list" do
      datasource = Datasource.create! valid_attributes
      delete :destroy, {:id => datasource.to_param}, valid_session
      expect(response).to redirect_to(datasources_path)
    end
  end

end
